# Generated by Django 5.2.1 on 2025-06-07 07:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_management',
            name='Category',
            field=models.CharField(choices=[('bloodTest', 'Blood Test'), ('urineTest', 'Urine Test'), ('gulcoseTest', 'Gulcose Test'), ('biopsy', 'Biopsy'), ('lipidProfile', 'Lipid Profile'), ('liverFunctionTests', 'Liver Function Tests')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_management',
            name='Feature_images',
            field=models.ImageField(default=1, upload_to='feature_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_management',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_management',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='service_management',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_management',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='OtherImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='other_images/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_images', to='service_management.service_management')),
            ],
        ),
    ]
