# Generated by Django 5.2.1 on 2025-06-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0002_service_management_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherimage',
            old_name='image',
            new_name='other_images',
        ),
        migrations.RenameField(
            model_name='service_management',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='service_management',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='service_management',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='service_management',
            old_name='Price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='service_management',
            name='Feature_images',
        ),
        migrations.AddField(
            model_name='service_management',
            name='feature_image',
            field=models.ImageField(default=1, upload_to='feature_image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_management',
            name='sub_Category',
            field=models.CharField(choices=[('wbcTest', 'WBC Test'), ('rbcTest', 'RBC Test'), ('platelets', 'Platelets')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
