# Generated by Django 5.2.1 on 2025-06-07 16:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='popup_images/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
